FROM quay-proxy.ci.openshift.org/openshift/ci:openshift_release_rhel-9-release-golang-1.26-openshift-5.0 AS builder
WORKDIR /go/src/k8s.io/autoscaler/vertical-pod-autoscaler
COPY . .
RUN go build ./pkg/admission-controller
RUN go build ./pkg/updater
RUN go build ./pkg/recommender

FROM registry.ci.openshift.org/ocp/5.0:base-rhel9
COPY --from=builder \
    /go/src/k8s.io/autoscaler/vertical-pod-autoscaler/admission-controller \
    /go/src/k8s.io/autoscaler/vertical-pod-autoscaler/updater \
    /go/src/k8s.io/autoscaler/vertical-pod-autoscaler/recommender \
    /usr/bin/
LABEL summary="Vertical Pod Autoscaler for OpenShift and Kubernetes"
